### PR TITLE
Various julia 0.7/1.0 fixes

### PR DESCRIPTION
**Pull request by tkluck**
This branch updates syntax and function calls for 0.7/1.0. WARNING: I've made no attempt to stay compatible with 0.6 or older.

### CODE REVIEW

**Comment by tkluck** [comment]
FYI, I opened a bug report for the `transcode` issue I found while working on this: https://github.com/JuliaLang/julia/issues/28612

**Comment by PerezHz** [comment]
Since these changes are breaking wrt 0.5 and 0.6, perhaps appveyor and travis should be updated accordingly?

**Comment by tkluck** [comment]
Good point @PerezHz . Just pushed the changes to the CI scripts; let's see what the results are!

**Comment by PerezHz** [comment]
Great, @tkluck! And many thanks for your work on this! I also worked on fixing some other depwarns, and submitted those changes as a PR in your fork; see the following link for more details: [https://github.com/tkluck/Expect.jl/pull/1](https://github.com/tkluck/Expect.jl/pull/1), hope this helps!

**Pull request closed without merging**
